"""empty message

Revision ID: 19d76a268a98
Revises: c3bf7160a888
Create Date: 2024-07-18 22:32:32.840461

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19d76a268a98"
down_revision: Union[str, None] = "c3bf7160a888"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rounds", "map")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rounds", sa.Column("map", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
