"""empty message

Revision ID: 1bb60c675bf1
Revises: 
Create Date: 2024-07-18 21:27:47.221298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb60c675bf1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_factions')),
    sa.UniqueConstraint('name', name=op.f('uq_factions_name'))
    )
    op.create_table('maps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maps')),
    sa.UniqueConstraint('name', name=op.f('uq_maps_name'))
    )
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('guid', name=op.f('uq_players_guid'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('faction_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], name=op.f('fk_jobs_faction_id_factions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('name', name=op.f('uq_jobs_name'))
    )
    op.create_table('rounds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('map', sa.String(), nullable=False),
    sa.Column('winning_faction', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['winning_faction'], ['factions.id'], name=op.f('fk_rounds_winning_faction_factions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds'))
    )
    op.create_table('players_rounds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('round_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_players_rounds_job_id_jobs')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_players_rounds_player_id_players')),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_players_rounds_round_id_rounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players_rounds')),
    sa.UniqueConstraint('player_id', 'round_id', name=op.f('uq_players_rounds_player_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players_rounds')
    op.drop_table('rounds')
    op.drop_table('jobs')
    op.drop_table('players')
    op.drop_table('maps')
    op.drop_table('factions')
    # ### end Alembic commands ###
