"""empty message

Revision ID: 5580fff760e3
Revises: b41488fbb05e
Create Date: 2024-07-17 23:47:12.006490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5580fff760e3'
down_revision: Union[str, None] = 'b41488fbb05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.add_column('players_rounds', sa.Column('job_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(op.f('fk_players_rounds_job_id_jobs'), 'players_rounds', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_players_rounds_job_id_jobs'), 'players_rounds', type_='foreignkey')
    op.drop_column('players_rounds', 'job_id')
    op.drop_table('jobs')
    # ### end Alembic commands ###
