"""empty message

Revision ID: 86e97f3be678
Revises: 19d76a268a98
Create Date: 2024-09-07 19:28:05.248688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e97f3be678'
down_revision: Union[str, None] = '19d76a268a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('winning_score', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('summary_message', sa.Text(), nullable=True))
    op.alter_column('rounds', 'map_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rounds', 'map_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('rounds', 'summary_message')
    op.drop_column('rounds', 'winning_score')
    # ### end Alembic commands ###
