"""empty message

Revision ID: b41488fbb05e
Revises: d8025f3c8fe8
Create Date: 2024-07-17 23:14:10.351142

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b41488fbb05e"
down_revision: Union[str, None] = "d8025f3c8fe8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("name", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "name")
    # ### end Alembic commands ###
