"""empty message

Revision ID: be0462ce33d4
Revises: 8c2aea4229c3
Create Date: 2024-07-18 22:29:08.960207

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be0462ce33d4"
down_revision: Union[str, None] = "8c2aea4229c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rounds", sa.Column("map_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        op.f("fk_rounds_map_id_maps"), "rounds", "maps", ["map_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_rounds_map_id_maps"), "rounds", type_="foreignkey")
    op.drop_column("rounds", "map_id")
    # ### end Alembic commands ###
