"""empty message

Revision ID: c11a00e35128
Revises: ef6a1ab56097
Create Date: 2024-07-18 14:37:45.566341

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c11a00e35128"
down_revision: Union[str, None] = "ef6a1ab56097"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "factions",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factions")),
    )
    op.add_column(
        "rounds", sa.Column("winning_faction", sa.String(length=100), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_rounds_winning_faction_factions"),
        "rounds",
        "factions",
        ["winning_faction"],
        ["id"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_rounds_winning_faction_factions"), "rounds", type_="foreignkey"
    )
    op.drop_column("rounds", "winning_faction")
    op.drop_table("factions")
    # ### end Alembic commands ###
