name: Update

on: workflow_dispatch
#   schedule:
#     - cron: '0 */2 * * *'
env:
  GITHUB_ACTION: "true"
jobs:
  uppdate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # environment: production
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup python dependencies
        run: |
          python -m pip install uv
          uv venv
          uv pip install --requirement requirements.txt
          .venv/bin/python -m src
          git config --global user.name 'Ghost'
          git config --global user.email 'ghost@github.com'
          git add src/
          git commit -m "Automated addition of the yaml files"
          git push